name: connected
channels: !!python/object/new:ruamel_yaml.comments.CommentedSeq
  listitems:
  - spacy
  - defaults
  state:
    _yaml_format: !!python/object:ruamel_yaml.comments.Format
      _flow_style: false
    _yaml_line_col: !!python/object:ruamel_yaml.comments.LineCol
      col: 2
      data:
        0:
        - 1
        - 4
        1:
        - 2
        - 4
      line: 1
dependencies:
- mkl=11.3.3=0
- numpy=1.11.1=py35_0
- openssl=1.0.2h=2
- pip=8.1.2=py35_0
- python=3.5.2=0
- readline=6.2=2
- scipy=0.18.0=np111py35_0
- setuptools=26.1.1=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - appnope==0.1.0
  - cycler==0.10.0
  - decorator==4.0.10
  - entrypoints==0.2.2
  - funcsigs==0.4
  - ipykernel==4.4.1
  - ipython==5.1.0
  - ipython-genutils==0.1.0
  - ipywidgets==5.2.2
  - jinja2==2.8
  - jsonschema==2.5.1
  - jupyter==1.0.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.1.1
  - markupsafe==0.23
  - matplotlib==1.5.2
  - mistune==0.7.3
  - mock==1.3.0
  - nbconvert==4.2.0
  - nbformat==4.1.0
  - networkx==1.11
  - nose==1.3.7
  - notebook==4.2.2
  - pandas==0.18.1
  - pbr==1.8.1
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - prompt-toolkit==1.0.7
  - ptyprocess==0.5.1
  - pygments==2.1.3
  - pygobject==3.18.2
  - pyparsing==2.1.8
  - python-dateutil==2.5.3
  - pytz==2016.6.1
  - pyzmq==15.4.0
  - qtconsole==4.2.1
  - seaborn==0.7.1
  - simplegeneric==0.8.1
  - six==1.10.0
  - terminado==0.6
  - tornado==4.4.1
  - traitlets==4.2.2
  - watermark==1.3.3
  - wcwidth==0.1.7
  - widgetsnbextension==1.2.6
prefix: /Users/pbaumgartner/anaconda3/envs/connected

